# Generated by Django 4.0.4 on 2022-04-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface'), ('M', 'Monitor')], max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('IR', 'In-Repair'), ('S', 'Shipped'), ('D', 'Damaged'), ('R', 'Repaired'), ('JO', 'Junk Out')], max_length=50)),
                ('ship_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('De', 'Delivered'), ('WO', 'With Owner'), ('WC', 'With Company')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('department', models.CharField(choices=[('Clinical Ops', 'Clinical Operations'), ('Coaching', 'Coaching'), ('Com', 'Commerical'), ('data', 'Data'), ('Eng', 'Engineering'), ('Exec', 'Executive'), ('Fin', 'Finance'), ('IT', 'IT'), ('Legal', 'Legal'), ('MKTG', 'Marketing'), ('MX', 'Member Experience'), ('Ops', 'Operations'), ('Prod', 'Product'), ('P&C', 'Program & Content'), ('Strat Init', 'Strategic Initatives'), ('Strat', 'Strategy'), ('Tal&PPL', 'Talent & People')], max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.IntegerField()),
                ('device', models.ManyToManyField(to='main_app.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
