# Generated by Django 3.0.5 on 2022-04-18 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface'), ('M', 'Monitor')], max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('IR', 'In-Repair'), ('S', 'Shipped'), ('D', 'Damaged'), ('R', 'Repaired'), ('JO', 'Junk Out')], max_length=50)),
                ('is_shipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.IntegerField()),
                ('device', models.ManyToManyField(to='main_app.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Clinical Ops', 'Clinical Operations'), ('Coaching', 'Coaching'), ('Com', 'Commerical'), ('data', 'Data'), ('Eng', 'Engineering'), ('Exec', 'Executive'), ('Fin', 'Finance'), ('IT', 'Information Technology'), ('Legal', 'Legal'), ('MKTG', 'Marketing'), ('MX', 'Member Experience'), ('Ops', 'Operations'), ('Prod', 'Product'), ('P&C', 'Program & Content'), ('Strat Init', 'Strategic Initatives'), ('Strat', 'Strategy'), ('Tal&PPL', 'Talent & People')], max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Device')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
