# Generated by Django 3.0.5 on 2022-04-18 22:58

from django.db import migrations, models

#ADDED SHIP STATUS DROPDOWN MENU ADMIN
class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='device',
            name='ship_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('De', 'Delivered'), ('WO', 'With Owner'), ('WC', 'With Company')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
