# Generated by Django 3.0.5 on 2022-04-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='devices',
            field=models.ManyToManyField(blank=True, to='main_app.Device'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='devices',
            field=models.ManyToManyField(blank=True, to='main_app.Device'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ship_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('WO', 'With Owner'), ('WC', 'With Company')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
