# Generated by Django 3.0.5 on 2022-04-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220425_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('Surface', 'Microsoft Surface')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('In-Repair', 'IR'), ('Shipped', 'S'), ('Damaged', 'D'), ('Repaired', 'R'), ('Junk Out', 'JO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Clinical Operations', 'Clinical Ops'), ('Coaching', 'Coaching'), ('Commerical', 'Com'), ('Data', 'data'), ('Engineering', 'Eng'), ('Executive', 'Exec'), ('Finance', 'Fin'), ('IT', 'IT'), ('Legal', 'Legal'), ('Marketing', 'MKGT'), ('Member Experience', 'MX'), ('Operations', 'Ops'), ('Product', 'Prod'), ('Program & Content', 'P&C'), ('Strategic Initatives', 'Strat Init'), ('Strategy', 'Strat'), ('Talent & People', 'Tal&PPL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('Surface', 'Microsoft Surface')], max_length=50),
        ),
    ]
