# Generated by Django 3.0.5 on 2022-04-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220423_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='add',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
