# Generated by Django 3.0.5 on 2022-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220423_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface')], max_length=50),
        ),
    ]
