# Generated by Django 4.0.3 on 2022-04-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('MBA', 'MacBook Air'), ('MBP', 'MacBook Pro'), ('S', 'Microsoft Surface')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='ship_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('WO', 'With Owner'), ('WC', 'With Company')], max_length=50),
        ),
    ]
