# Generated by Django 3.0.5 on 2022-04-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Clinical Ops', 'Clinical Operations'), ('Coaching', 'Coaching'), ('Com', 'Commerical'), ('data', 'Data'), ('Eng', 'Engineering'), ('Exec', 'Executive'), ('Fin', 'Finance'), ('IT', 'IT'), ('Legal', 'Legal'), ('MKTG', 'Marketing'), ('MX', 'Member Experience'), ('Ops', 'Operations'), ('Prod', 'Product'), ('P&C', 'Program & Content'), ('Strat Init', 'Strategic Initatives'), ('Strat', 'Strategy'), ('Tal&PPL', 'Talent & People')], max_length=50),
        ),
    ]
