# Generated by Django 4.0.3 on 2022-04-19 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_device_device_type_alter_device_ship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='devices',
            field=models.ForeignKey(default='Unassigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.device'),
        ),
    ]
