# Generated by Django 4.0.3 on 2022-04-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_employee_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.device'),
        ),
    ]
