# Generated by Django 4.0.3 on 2022-04-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_employee_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='devices',
        ),
        migrations.AddField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
