# Generated by Django 4.0.3 on 2022-04-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_device_employee_employee_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='devices',
        ),
        migrations.AddField(
            model_name='employee',
            name='devices',
            field=models.ManyToManyField(blank=True, to='main_app.device'),
        ),
    ]
