# Generated by Django 4.0.4 on 2022-04-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_inventory_total_stock_inventory_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='value',
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='device',
        ),
        migrations.AddField(
            model_name='inventory',
            name='device',
            field=models.ManyToManyField(to='main_app.device'),
        ),
    ]
