# Generated by Django 4.0.4 on 2022-04-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_inventory_value_inventory_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='device',
            field=models.ManyToManyField(blank=True, to='main_app.device'),
        ),
    ]
