# Generated by Django 4.0.3 on 2022-04-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_inventory_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='device',
            new_name='devices',
        ),
    ]
