# Generated by Django 4.0.4 on 2022-04-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_device_inventory_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
