# Generated by Django 4.0.4 on 2022-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_employee_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='in_stock',
            new_name='add',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='device',
            field=models.ManyToManyField(to='main_app.device'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='devices',
            field=models.ManyToManyField(blank=True, to='main_app.device'),
        ),
    ]
